sudo: false

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock 

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - echo no | npm install -g grunt-cli
    - npm install
    - grunt compile

matrix:
  include:
    - stage: lint
      language: node_js
      os: linux
      node_js: "8"
      script: grunt lint

    - stage: deploy
      if: branch = release
      language: node_js 
      node_js: "8"
      before_deploy:
          - cd bin/dist
      deploy:
        provider: npm
        email: "peter@tangrasoft.com"
        api_key:
          secure: "e9SvpVI5TOQddEKKyChUuKC2u7ofBKSIdNqxfdOvhF27WhdpwF/IV3C44TNZJ2OzrgQbCt8D3wNSa6gGIjk3DVWHbC3zMcY9Dytu/4+8YDqZOGw0dWKXBYkdqDww+92VQBwbyZ1wZqBYCWlNpAnudN4gV/Am8yMtbltEM9cjZXwGIn2DIV/qUNu/vXlSs4ejoGBe7Ot4j6iMH4govA6t1WDlBwyb4vZQtGBhKpDyTq30qPzPV9CnrgmYonJ8hPLi2B9izm/3F/eBhueVH54Ignh0OKGA0zs3+zRpA++D+5tuxwp3ZwrNT6G7nOVEugzTXlh69UjoN2Ig/fVFQ62AHVmQnGN788r6Gi3pRx9tZeLIq50N3TPGC3fArYAachDVB9YvNl3JO691cSIrp9xMEoDWnVzrMYU77IvLX69RlmYMzCAgSlnu3jHUD7cR/Exsx1HSbvgmva9Qnkk16kKyCRfZxBshj5Xml0LlyEWZZu1XcW2m/D5v/G1cSIC8dKk2VODMt2nGY9P+q/1CbmFnKnE/1jesgEZbbYahtD3sG4FL7Yrk7IOGyJyXj4scHrZwbO5CLt05w20Z2+cHSDP9iBeaygSvRrlZ3pk8Cth6fFFXJfyKxgk/aquANt2/eGlmvC+uz5eOzBHnXqb2/kXTFFr/0FdtLuJ9AemNi+cFdyc="
        skip_cleanup: true
        on:
          branch: release